apiVersion: v1
kind: Pod
metadata:
  name: sensitive
spec:
  containers:
  - name: sensitive
    image: nginx
    volumeMounts:
    - mountPath: /test-pd
      name: sensitive-volume
  volumes:
  - name: sensitive-volume
    hostPath:
      # directory location on host
      path: /etc
      # this field is optional
      type: Directory